import type { Metadata } from 'next'
import { PageShell, PageHero, Section } from '@/components/content-page'

export const metadata: Metadata = {
  title: 'Research & Data',
  description:
    'Open datasets and standardized cytometry annotation tools from the SOULCAP Foundation.',
}

export default function ResearchDataPage() {
  return (
    <PageShell>
      <PageHero
        eyebrow="Research & Data"
        title="Open Datasets & Tools"
        intro="Standardized annotation tools and open-access reference datasets for the global research community."
      />

      <Section title="Standardized Cytometry Annotation Toolkit">
        <p>
          Download SOULCAP&apos;s standardized flow cytometry cell population Annotation, Metadata
          &amp; Ontologies tool to help you identify and label your cell populations.
        </p>
        <p>
          We maintain strategic partnerships with leading research and industrial institutions to
          ensure the SOULCAP Annotation, Metadata &amp; Ontologies tools are rigorously tested
          before public release.
        </p>
        <p className="font-medium text-gray-500">
          👉 Download Annotation, Metadata &amp; Ontologies (Coming soon)
        </p>
      </Section>

      <Section title="Public Datasets" alt>
        <p>
          SOULCAP believes that scientific progress accelerates when data flows freely and securely
          across institutional and geographic boundaries. Our commitment extends beyond responsible
          stewardship to active data sharing with partner organizations and the global research
          community.
        </p>
        <p>
          SOULCAP hosts datasets used in research related to the SOULCAP Foundation — anything that
          pushes forward standardized cell annotation in research is welcome.
        </p>
        <p className="font-medium text-gray-500">
          👉 Browse SOULCAP hosted datasets generated by SOULCAP and the broader research community
          (Coming soon)
        </p>
      </Section>

      <Section title="Contribute!">
        <p>
          When you contribute data to SOULCAP, it serves multiple specific purposes within our
          standardization mission. By contributing, your data becomes part of a global reference
          resource that accelerates consensus and enables AI-ready frameworks for immunology and
          clinical translation. Contributors retain control through transparent IP and licensing
          policies.
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>Developing Universal Standards:</strong> your cytometry data helps establish
            globally accepted gating strategies and cell population definitions used by researchers
            worldwide.
          </li>
          <li>
            <strong>Validating Annotation Software:</strong> contributed datasets train and test
            automated annotation algorithms, ensuring they perform accurately across diverse
            populations and experimental conditions.
          </li>
        </ul>
        <p className="font-medium text-gray-500">👉 Contribute Data to SOULCAP (Coming soon)</p>
      </Section>
    </PageShell>
  )
}
